- alias: HDMI Switch
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.hdmi_switch
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/switch/hdmi"
      payload_template: "{{ states('input_select.hdmi_switch') }}"

- alias: Night Light ON
  hide_entity: True
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.under_bed_light
    data:
      rgb_color: [15, 0, 15]
      transition: 5

- alias: Night Light OFF
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: 
      - light.under_bed_light

- alias: Turn off all lights
  hide_entity: True
  trigger:
    platform: time
    at: '23:59:55'
  condition:
    condition: state
    entity_id: device_tracker.kevins_macbook
    state: away
  action:
    service: light.turn_off
    entity_id:
      - group.all_lights
    data:
      transition: 30 

- alias: Sunset Desk Light
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
  action: 
    service: light.turn_on
    entity_id:
      - light.desk_lamp

- alias: 'Auto Renew SSL Cert'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: 'SSL expiry notification'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'

- alias: 'Set Spotify Volume'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{ states.input_number.spotify_volume.state }}'

# ios notifications
# turn off lights
- alias: Notify Kevin his Lights are on
  hide_entity: True
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.kevin_panaros_iphone_x
  condition:
    condition: state
    entity_id: group.all_lights
    state: 'on'
  action:
  - service: notify.ios_kevin_panaros_iphone_x
    data:
      message: 'You left a light on at home'
# kept for example purposes
#      data:
#        push:
#          category: 'lightsoff'
  - service: light.turn_off
    data:
      entity_id: group.all_lights

- alias: Handle iOS Turn Off Lights Notification
  hide_entity: True
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_LIGHTS
  action:
   entity_id: group.all_lights
   service: light.turn_off

- alias: Kevin's Working on his Macbook
  hide_entity: True
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.device_tracker.kevins_macbook.last_updated)) > 300 }}'
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/device_tracker/mqtt/macbook"
      payload: "away"

- alias: "Huzzah Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_number.huzzah_animation_speed
  action:
    service: mqtt.publish
    data_template:
      topic: "homeassistant/light/lamp/rgb/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
