- alias: HDMI Switch
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.hdmi_switch
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/switch/hdmi"
      payload_template: "{{ states('input_select.hdmi_switch') }}"

- alias: Night Light ON
  hide_entity: True
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.under_bed_light
    data:
      rgb_color: [15, 0, 15]
      transition: 5

- alias: Night Light OFF
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: 
      - light.under_bed_light

- alias: Turn off all lights
  hide_entity: True
  trigger:
    platform: time
    at: '23:59:55'
  action:
    service: light.turn_off
    entity_id:
      - group.all_lights
    data:
      transition: 30 

- alias: Sunset Desk Light
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
  action: 
    service: light.turn_on
    entity_id:
      - light.desk_lamp

- alias: 'Auto Renew SSL Cert'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: 'SSL expiry notification'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.ios_kevin_panaros_iphone
    data:
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'

- alias: 'Set Spotify Volume'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{ states.input_number.spotify_volume.state }}'

# ios notifications
# turn off lights
- alias: Notify Kevin his Lights are on
  hide_entity: True
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.kevin_panaros_iphone
  condition:
    condition: state
    entity_id: group.all_lights
    state: 'on'
  action:
    service: notify.ios_kevin_panaros_iphone
    data:
      message: 'You left a light on at home'
      data:
        push:
          category: 'lightsoff'
 
- alias: Handle iOS Turn Off Lights Notification
  hide_entity: True
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_LIGHTS
  action:
   entity_id: group.all_lights
   service: light.turn_off
