homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# For alexa component
alexa:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: command_line
    name: SSL cert expiry
    scan_interval: 10800
    command: !secret duck_dns_update_command

# Text to speech
tts:
  - platform: google

# Kev additions
ios:
  push:
    categories:
      - name: Lights
        identifier: 'lightsoff'
        actions:
          - identifier: 'TURN_OFF_LIGHTS'
            title: 'Turn Off Lights'
            activationMode: background
            authenticationRequired: no
            destructive: no
          - identifier: 'KEEP_LIGHTS_ON'
            title: 'Keep Lights On'
            activationMode: background
            authenticationRequired: no
            destructive: yes
            
        
mqtt:
  broker: !secret mrpalmer

media_player:
  - platform: cast
  - platform: kodi
    host: !secret fluffhead 
    name: fluffhead
  - platform: spotify
    client_id: !secret media_player_spotify_client_id
    client_secret: !secret media_player_spotify_client_secret

#binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
light: !include light.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
zone: !include zones.yaml
