- platform: nmap_tracker
  hosts: !secret kevins_iphone_ip
- platform: mqtt
  devices:
    backpack_beacon: homeassistant/device_tracker/ble/beacon
    kevins_macbook: homeassistant/device_tracker/mqtt/macbook
