- platform: mqtt_json
  name: Under Bed Light
  state_topic: "homeassistant/light/bed/rgb" 
  command_topic: "homeassistant/light/bed/rgb/set" 
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0
- platform: mqtt
  command_topic: "homeassistant/light/desk/switch"
  state_topic: "homeassistant/light/desk/status"
  name: "Desk Lamp"
- platform: mqtt_json
  name: Sub Lamp
  state_topic: "homeassistant/light/lamp/rgb"
  command_topic: "homeassistant/light/lamp/rgb/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle 
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

